In [10]:
import numpy as np

In [11]:
revenue=np.array([[100,200,220],[24,26,40],[12,18,20]])
expenses=np.array([[60,90,100],[10,16,20],[8,10,10]])

In [12]:
profit=revenue-expenses
profit

array([[ 40, 110, 120],
       [ 14,  10,  20],
       [  4,   8,  10]])

In [13]:
price_per_unit=([1000,400,1200])
units=np.array([[30,40,50],[5,10,15],[2,5,7]])

In [14]:
price_per_unit*units

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [15]:
np.dot(price_per_unit,units)

array([34400, 50000, 64400])